name: SwitchFlame
favicon: null
layout_spectrum: 0.26456
typography_spectrum: 0.13688
title: SwitchFlame
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
